name: Validation Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-dotnet@v3

    - name: Run Tests
      working-directory: ./src
      run: dotnet test